.build: &build
  services:
    - name: docker
      options:
        rootlessBuildkitd:
          enabled: true
  env:
    IMAGE: ${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}
  stages:
    - name: docker build & push
      script: |
        docker buildx build -t ${IMAGE}:latest -t ${IMAGE}:${CNB_BRANCH} --platform linux/amd64,linux/arm64 --push .

.push: &push
  stages:
    - name: auto-tag
      image: cnbcool/git-auto-tag:latest
      settings:
        blockWhenFail: false
        branch: $CNB_BRANCH
        repoUrlHttps: $CNB_REPO_URL_HTTPS
      exports:
        tag: NEW_TAG
    - name: show tag
      script: echo $NEW_TAG

main:
  push:
    - *push

$:
  vscode:
    - docker:
        image: docker.cnb.cool/scaffold/examples/nodejs:latest
      services:
        - vscode
        - docker
  tag_push:
    - *build

  web_trigger_view:
    vscode:
      - runner:
          cpus: 4
        services:
          - name: vscode
            options:
              onlyPreview: true
              launch: |
                # 启动docker服务并且挂在到8686端口
                docker run -d --rm -p 8686:3000 --name ${CNB_REPO_SLUG_LOWERCASE} ${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}
              keepAliveTimeout: 3600000
              daemon: false
          - docker
