.build-full: &build-full
  services:
    - name: docker
      options:
        rootlessBuildkitd:
          enabled: true
  env:
    IMAGE: ${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}
  stages:
    - name: docker build & push
      script: |
        docker buildx build \
          --build-arg MODELGATE_EDITION=full \
          --cache-from type=registry,ref=${IMAGE}:full-cache-amd64 \
          --cache-from type=registry,ref=${IMAGE}:full-cache-arm64 \
          --cache-to type=registry,ref=${IMAGE}:full-cache-amd64,mode=max \
          --cache-to type=registry,ref=${IMAGE}:full-cache-arm64,mode=max \
          -t ${IMAGE}:latest -t ${IMAGE}:${CNB_BRANCH} \
          --platform linux/amd64,linux/arm64 --push .

.build-lite: &build-lite
  services:
    - name: docker
      options:
        rootlessBuildkitd:
          enabled: true
  env:
    IMAGE: ${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}
  stages:
    - name: docker build & push lite
      script: |
        docker buildx build \
          --build-arg MODELGATE_EDITION=lite \
          --cache-from type=registry,ref=${IMAGE}:lite-cache-amd64 \
          --cache-from type=registry,ref=${IMAGE}:lite-cache-arm64 \
          --cache-to type=registry,ref=${IMAGE}:lite-cache-amd64,mode=max \
          --cache-to type=registry,ref=${IMAGE}:lite-cache-arm64,mode=max \
          -t ${IMAGE}:lite \
          --platform linux/amd64,linux/arm64 --push .

.push: &push
  stages:
    - name: auto-tag
      image: cnbcool/git-auto-tag:latest
      settings:
        blockWhenFail: false
        branch: $CNB_BRANCH
        repoUrlHttps: $CNB_REPO_URL_HTTPS
      exports:
        tag: NEW_TAG
    - name: show tag
      script: echo $NEW_TAG

main:
  push:
    - *push
    - name: sync
      runner:
        cpus: 1
      imports: https://cnb.cool/ecustcic/key/-/blob/main/env.yml
      stages:
        - name: sync to github
          image: tencentcom/git-sync
          settings:
            target_url: https://github.com/ECUSTCIC-CodeHub/ModelGate.git
            auth_type: https
            username: ${GITHUB_USERNAME}
            password: ${GITHUB_ACCESS_TOKEN}
            force: true

$:
  vscode:
    - docker:
        image: docker.cnb.cool/scaffold/examples/nodejs:latest
      services:
        - vscode
        - docker
  tag_push:
    - *build-full
    - *build-lite